---
title: "Association"
output: html_document
date: "2024-05-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
PATH = "/Users/aliarabat/Documents/PhD/projects/change-predictor"
association_result <- read.csv(paste(PATH, "Files", "association_rule.csv", sep="/"))
association_result$confidence <- association_result$confidence*100
association_max <- read.csv(paste(PATH, "Files", "max_conf_per_pro.csv", sep="/"))
association_max$Confidence <- association_max$Confidence*100
# association_result <- association_result$confidence
```


```{r}
association_max
```


```{r}
plot_single_boxplot<-function(data, x, y, x_lab, y_lab, breaks=NULL){
  p <- data %>%
    ggplot(aes_string(x = factor(0), y = y))
  if(is.null(breaks)==FALSE) {
    p<-p+scale_y_continuous(trans = "log1p", breaks=breaks)
  }
  p<-p+
    geom_boxplot(fatten=0.5) + 
    theme_linedraw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      legend.position = "top",
      axis.line = element_line(colour = "black"),
      axis.text = element_text(size = 11, color = "grey30"),
      axis.title = element_text(size = 12)
    )+
    labs(x = "", y = y_lab) +
    scale_x_discrete(breaks = NULL)+
    scale_y_continuous(labels = c('0%', '25%', '50%', '75%', '100%'))
  
  return(p)
}
```

```{r}
p1<-
  plot_single_boxplot(
    association_result, 
      x = factor(0), 
      y = "confidence", 
      x_lab = "", 
      y_lab = "Confidence (%)"
  )
p1
```

```{r}
p2<-
  plot_single_boxplot(
    association_max, 
      x = factor(0), 
      y = "Confidence", 
      x_lab = "", 
      y_lab = "Confidence (%)"
  )
p2
```
