---
title: "Accuracies"
output: html_document
date: "2023-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("scales")
library(ggplot2)
library(ScottKnottESD)
```


```{r}
PATH = "/Users/aliarabat/Documents/PhD/projects/change-predictor"
first_feat_impo <- read.csv(paste(PATH, "Results", "Feature_importance", "first_feat_impo.csv", sep="/"))
second_feat_impo <- read.csv(paste(PATH, "Results", "Feature_importance", "second_feat_impo.csv", sep="/"))
all_cros_chan_count <- read.csv(paste(PATH, "Files", "all_cros_chan_count.csv", sep="/"))
dep_chan_count <- read.csv(paste(PATH, "Files", "dep_chan_count.csv", sep="/"))
deps_evolution <- read.csv(paste(PATH, "Files", "Preliminary", "deps_evolution.csv", sep="/"))
deps_ident <- read.csv(paste(PATH, "Files", "Preliminary", "deps_ident.csv", sep="/"))
```

```{r}
# An example dataset: The 1,000 variable importance scores of 9 software metrics. 
# The scores are generated by the Random Forests technique using 1,000 out-of-sample bootstrap.
# example

# Using Non-Parametric ScottKnott ESD test
# sk <- sk_esd(first_feat_impo)
# plot(sk)

sk <- sk_esd(second_feat_impo)

# sk <- sk_esd(third_feat_impo)
sk
```

```{r}
plot_single_boxplot<-function(data, x, y, x_lab, y_lab, breaks=NULL){
  p <- data %>%
    ggplot(aes_string(x = factor(0), y = y))
  if(is.null(breaks)==FALSE) {
    p<-p+scale_y_continuous(trans = "log1p", breaks=breaks)
  }
  p<-p+
    geom_boxplot(fatten=0.5) + 
    theme_linedraw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      legend.position = "top",
      axis.line = element_line(colour = "black"),
      axis.text = element_text(size = 13, color = "grey30"),
      axis.title = element_text(size = 14)
    )+
    labs(x = "", y = y_lab) +
    scale_x_discrete(breaks = NULL)
  
  return(p)
}
all_cros_chan_count
```


```{r}
p1<-
  plot_single_boxplot(
  all_cros_chan_count, 
      x = factor(0), 
      y = "count", 
      x_lab = "", 
      y_lab = "# of changes"
      # breaks = c(0,1,10, 100, 1000)
  )
p1
```

```{r}
p2<-
  plot_single_boxplot(
  dep_chan_count, 
      x = factor(0), 
      y = "Count", 
      x_lab = "", 
      y_lab = "# of changes"
      # breaks = c(0,1,10, 100, 1000)
  )
p2
```





```{r}
p3<-deps_evolution %>%
  mutate(Year=paste(Year, ""))%>%
  ggplot(aes(x=Year, y = percentage, colour = Status, group=Status)) + 
  geom_line() +
  geom_point() +
  theme_linedraw() +
  theme(
    panel.grid.major=element_line(colour="grey"),
    panel.grid.minor=element_line(colour="grey"),
    legend.position='top',
    legend.justification='left',
    legend.direction='horizontal',
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=0.9, size=10,colour = "black"),
          legend.text = element_text(size=9),axis.title.y = element_text(size=12,),
      axis.title.x = element_text(size=12,),
          axis.text.y = element_text(size=10 ,colour="black")) + 
  xlab("Years")  +  
  ylab("% of dependent changes") + 
  scale_colour_discrete(name="")
p3
```

```{r}
plot_boxplot <- function(data, x, y, fill, x_lab, y_lab, fill_lab, breaks=NULL){
  p=data%>%
    ggplot() +
    geom_boxplot(aes_string(x=x, y=y, fill=fill), fatten=0.5, outlier.shape = NA)
  
  if (!is.null(breaks)){
    p<-p+scale_y_continuous(trans = "log1p", breaks = breaks)
  }
  p<-p+ 
    theme_linedraw() +
    theme(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),
      legend.position = "none",
      # legend.title = element_text(size = 6),
      # legend.text = element_text(size = 6),
      axis.line = element_line(colour = "black"),
      axis.text = element_text(size = 12, color = "grey30"),
      axis.title = element_text(size = 14)
    )+
    # stat_summary(fun.data = give.n, aes_string(x=x, y=y),vjust = -3, size=5, geom = "text", fun = "median", 
                   # position = position_dodge(width = 0.75))+
    labs(x = x_lab, y = y_lab, fill = fill_lab)
  
  return(p)
}
```

```{r}
p4<-plot_boxplot(
      deps_ident, 
      x='iden_type', 
      y='when_identified', 
      fill=NULL, 
      x_lab = "Rapidity types", 
      y_lab = "Duration (hours)", 
      fill_lab=NULL,
      breaks=c(0, 1, 10, 100, 1000, 10000)
    )
p4
```

